/**
 * PMBIDMATRIX - Seed Data Script
 * Populates MongoDB with realistic procurement demo data
 * Run: npx ts-node src/utils/seedData.ts
 */

import mongoose from 'mongoose';

// ─── Demo Suppliers ──────────────────────────────
export const seedSuppliers = [
  {
    name: 'Tata Steel Limited',
    code: 'SUP-TSL-001',
    email: 'procurement@tatasteel.com',
    contactPerson: 'Rajesh Kumar',
    phone: '+91-9876543210',
    address: '1, Bishops Gate, Jamshedpur',
    city: 'Jamshedpur',
    state: 'Jharkhand',
    country: 'India',
    gstNumber: '20AABCT1231Q1ZX',
    panNumber: 'AABCT1231Q',
    categories: ['Steel', 'Iron Ore', 'Ferro Alloys'],
    rating: 4.8,
    riskScore: 15,
    status: 'approved',
    performanceMetrics: { onTimeDelivery: 96, qualityScore: 98, priceCompetitiveness: 85, responseTime: 92 },
  },
  {
    name: 'Hindalco Industries',
    code: 'SUP-HIN-002',
    email: 'supply@hindalco.com',
    contactPerson: 'Priya Sharma',
    phone: '+91-9876543211',
    address: 'Century Bhawan, Dr. Annie Besant Road',
    city: 'Mumbai',
    state: 'Maharashtra',
    country: 'India',
    gstNumber: '27AABCH1234Q1ZX',
    panNumber: 'AABCH1234Q',
    categories: ['Aluminum', 'Copper', 'Non-Ferrous Metals'],
    rating: 4.5,
    riskScore: 22,
    status: 'approved',
    performanceMetrics: { onTimeDelivery: 93, qualityScore: 95, priceCompetitiveness: 88, responseTime: 87 },
  },
  {
    name: 'Asian Paints Limited',
    code: 'SUP-APL-003',
    email: 'bulk@asianpaints.com',
    contactPerson: 'Amit Desai',
    phone: '+91-9876543212',
    address: '6A Shantinagar, Santacruz East',
    city: 'Mumbai',
    state: 'Maharashtra',
    country: 'India',
    gstNumber: '27AAECA5765Q1ZX',
    panNumber: 'AAECA5765Q',
    categories: ['Paints', 'Coatings', 'Chemicals'],
    rating: 4.7,
    riskScore: 12,
    status: 'approved',
    performanceMetrics: { onTimeDelivery: 97, qualityScore: 99, priceCompetitiveness: 82, responseTime: 95 },
  },
  {
    name: 'Vedanta Resources',
    code: 'SUP-VED-004',
    email: 'procurement@vedanta.co.in',
    contactPerson: 'Suresh Patel',
    phone: '+91-9876543213',
    address: 'Vedanta Tower, Udaipur',
    city: 'Udaipur',
    state: 'Rajasthan',
    country: 'India',
    gstNumber: '08AABCV1234Q1ZX',
    panNumber: 'AABCV1234Q',
    categories: ['Zinc', 'Lead', 'Silver', 'Copper'],
    rating: 4.3,
    riskScore: 28,
    status: 'approved',
    performanceMetrics: { onTimeDelivery: 89, qualityScore: 91, priceCompetitiveness: 90, responseTime: 84 },
  },
  {
    name: 'Pidilite Industries',
    code: 'SUP-PID-005',
    email: 'b2b@pidilite.com',
    contactPerson: 'Meera Joshi',
    phone: '+91-9876543214',
    address: 'Regent Chambers, Nariman Point',
    city: 'Mumbai',
    state: 'Maharashtra',
    country: 'India',
    gstNumber: '27AAACN1234Q1ZX',
    panNumber: 'AAACN1234Q',
    categories: ['Adhesives', 'Sealants', 'Construction Chemicals'],
    rating: 4.6,
    riskScore: 18,
    status: 'approved',
    performanceMetrics: { onTimeDelivery: 94, qualityScore: 97, priceCompetitiveness: 86, responseTime: 91 },
  },
  {
    name: 'SKF India Limited',
    code: 'SUP-SKF-006',
    email: 'industrial@skf.com',
    contactPerson: 'Vikram Singh',
    phone: '+91-9876543215',
    address: 'Mahatma Gandhi Road',
    city: 'Pune',
    state: 'Maharashtra',
    country: 'India',
    gstNumber: '27AABCS1234Q1ZX',
    panNumber: 'AABCS1234Q',
    categories: ['Bearings', 'Seals', 'Lubricants', 'Maintenance Tools'],
    rating: 4.9,
    riskScore: 8,
    status: 'approved',
    performanceMetrics: { onTimeDelivery: 98, qualityScore: 99, priceCompetitiveness: 78, responseTime: 96 },
  },
  {
    name: 'Rubber Board Suppliers Consortium',
    code: 'SUP-RBS-007',
    email: 'export@rubberboard.org.in',
    contactPerson: 'Thomas Mathew',
    phone: '+91-9876543216',
    address: 'Rubber Board Complex',
    city: 'Kottayam',
    state: 'Kerala',
    country: 'India',
    gstNumber: '32AABCR1234Q1ZX',
    panNumber: 'AABCR1234Q',
    categories: ['Natural Rubber', 'Synthetic Rubber', 'Latex'],
    rating: 4.1,
    riskScore: 35,
    status: 'approved',
    performanceMetrics: { onTimeDelivery: 85, qualityScore: 88, priceCompetitiveness: 92, responseTime: 80 },
  },
  {
    name: 'BASF India Limited',
    code: 'SUP-BAS-008',
    email: 'india@basf.com',
    contactPerson: 'Klaus Weber',
    phone: '+91-9876543217',
    address: 'The Capital, C-70, G Block, BKC',
    city: 'Mumbai',
    state: 'Maharashtra',
    country: 'India',
    gstNumber: '27AABCB5678Q1ZX',
    panNumber: 'AABCB5678Q',
    categories: ['Chemicals', 'Catalysts', 'Coatings', 'Performance Materials'],
    rating: 4.7,
    riskScore: 14,
    status: 'approved',
    performanceMetrics: { onTimeDelivery: 95, qualityScore: 98, priceCompetitiveness: 75, responseTime: 93 },
  },
];

// ─── Demo Commodities ──────────────────────────
export const seedCommodities = [
  {
    name: 'Hot Rolled Steel Coil',
    category: 'steel',
    currentPrice: 58500,
    priceHistory: [55000, 56200, 57800, 58100, 57500, 58500],
    volatilityPercent: 12.5,
    riskScore: 45,
    trendDirection: 'up',
    hedgingRecommendation: 'Consider forward contracts for Q3 delivery - prices expected to rise 5-8%',
    unit: 'INR/MT',
  },
  {
    name: 'LME Copper Cathode',
    category: 'copper',
    currentPrice: 742000,
    priceHistory: [720000, 735000, 728000, 745000, 738000, 742000],
    volatilityPercent: 18.3,
    riskScore: 62,
    trendDirection: 'volatile',
    hedgingRecommendation: 'High volatility detected - hedge 60% of Q3 requirements via options strategy',
    unit: 'INR/MT',
  },
  {
    name: 'Aluminum Ingot',
    category: 'aluminum',
    currentPrice: 215000,
    priceHistory: [208000, 210000, 212500, 215000, 213000, 215000],
    volatilityPercent: 8.2,
    riskScore: 32,
    trendDirection: 'up',
    hedgingRecommendation: 'Moderate bullish trend - lock 40% at current levels',
    unit: 'INR/MT',
  },
  {
    name: 'Industrial Grade Chemicals',
    category: 'chemicals',
    currentPrice: 85000,
    priceHistory: [82000, 83500, 84000, 85500, 84800, 85000],
    volatilityPercent: 6.5,
    riskScore: 25,
    trendDirection: 'stable',
    hedgingRecommendation: 'Stable pricing - annual contracts recommended',
    unit: 'INR/KL',
  },
  {
    name: 'Decorative Paint (Premium)',
    category: 'paints',
    currentPrice: 450,
    priceHistory: [420, 430, 440, 445, 448, 450],
    volatilityPercent: 5.8,
    riskScore: 20,
    trendDirection: 'up',
    hedgingRecommendation: 'Gradual increase expected - negotiate volume discounts',
    unit: 'INR/Litre',
  },
  {
    name: 'Natural Rubber (RSS-4)',
    category: 'rubber',
    currentPrice: 178,
    priceHistory: [165, 170, 175, 172, 176, 178],
    volatilityPercent: 15.2,
    riskScore: 55,
    trendDirection: 'up',
    hedgingRecommendation: 'Seasonal price spike expected in monsoon - pre-purchase recommended',
    unit: 'INR/Kg',
  },
  {
    name: 'Deep Groove Ball Bearing (6205)',
    category: 'bearings',
    currentPrice: 320,
    priceHistory: [310, 315, 318, 320, 319, 320],
    volatilityPercent: 3.2,
    riskScore: 12,
    trendDirection: 'stable',
    hedgingRecommendation: 'Price stable - long-term contracts with annual escalation clause',
    unit: 'INR/Unit',
  },
];

// ─── Demo Auctions ───────────────────────────
export const seedAuctions = [
  {
    auctionNumber: 'AUC-2026-000001',
    type: 'reverse',
    title: 'Hot Rolled Steel Coils - Q3 2026 Requirement',
    description: 'Reverse auction for procurement of 5000 MT Hot Rolled Steel Coils for manufacturing plant at Jamshedpur',
    items: [
      { name: 'HR Steel Coil 2.5mm', quantity: 2000, unit: 'MT', estimatedPrice: 58500, category: 'Steel' },
      { name: 'HR Steel Coil 3.0mm', quantity: 1500, unit: 'MT', estimatedPrice: 59200, category: 'Steel' },
      { name: 'HR Steel Coil 4.0mm', quantity: 1500, unit: 'MT', estimatedPrice: 60100, category: 'Steel' },
    ],
    status: 'active',
    startTime: new Date(),
    endTime: new Date(Date.now() + 4 * 60 * 60 * 1000),
    rules: { minDecrement: 100, antiSnipingMins: 2, reservePrice: 55000 },
    totalBids: 24,
    currentBestBid: 56800,
  },
  {
    auctionNumber: 'AUC-2026-000002',
    type: 'reverse',
    title: 'Industrial Bearings - Annual Rate Contract',
    description: 'Annual rate contract for procurement of various SKF/NTN bearings for plant maintenance',
    items: [
      { name: 'Ball Bearing 6205', quantity: 5000, unit: 'Units', estimatedPrice: 320, category: 'Bearings' },
      { name: 'Roller Bearing 22210', quantity: 2000, unit: 'Units', estimatedPrice: 1850, category: 'Bearings' },
    ],
    status: 'scheduled',
    startTime: new Date(Date.now() + 24 * 60 * 60 * 1000),
    endTime: new Date(Date.now() + 28 * 60 * 60 * 1000),
    rules: { minDecrement: 5, antiSnipingMins: 2, reservePrice: 0 },
    totalBids: 0,
    currentBestBid: 0,
  },
];

// ─── Demo RFQs ──────────────────────────────
export const seedRFQs = [
  {
    rfqNumber: 'RFQ-2026-000001',
    title: 'Industrial Chemical Supply for Batch Production',
    description: 'Requirement for bulk industrial chemicals including solvents, catalysts, and specialty chemicals for Q3-Q4 2026',
    items: [
      { name: 'Sulfuric Acid (98%)', quantity: 500, unit: 'KL', estimatedPrice: 12000, category: 'Chemicals' },
      { name: 'Caustic Soda Flakes', quantity: 200, unit: 'MT', estimatedPrice: 38000, category: 'Chemicals' },
      { name: 'Toluene', quantity: 100, unit: 'KL', estimatedPrice: 75000, category: 'Chemicals' },
    ],
    category: 'Chemicals',
    status: 'published',
    startDate: new Date(),
    endDate: new Date(Date.now() + 14 * 24 * 60 * 60 * 1000),
  },
  {
    rfqNumber: 'RFQ-2026-000002',
    title: 'Paint & Coatings for Factory Refurbishment',
    description: 'Complete painting and coating solution for factory refurbishment project across 3 plants',
    items: [
      { name: 'Epoxy Floor Coating', quantity: 2000, unit: 'Litres', estimatedPrice: 650, category: 'Paints' },
      { name: 'Anti-corrosive Primer', quantity: 5000, unit: 'Litres', estimatedPrice: 380, category: 'Paints' },
      { name: 'Industrial Top Coat', quantity: 3000, unit: 'Litres', estimatedPrice: 520, category: 'Paints' },
    ],
    category: 'Paints',
    status: 'evaluation',
    startDate: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000),
    endDate: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000),
  },
];

console.log('📦 Seed data definitions loaded successfully.');
console.log(`   → ${seedSuppliers.length} Suppliers`);
console.log(`   → ${seedCommodities.length} Commodities`);
console.log(`   → ${seedAuctions.length} Auctions`);
console.log(`   → ${seedRFQs.length} RFQs`);
console.log('');
console.log('To seed into MongoDB, connect to the database and import these arrays.');
